const FIN_SHEET='Personal Finance Transactions';
const FIN_HEADERS=['ID','Date','Account','Payee / Description','Category','Subcategory','Activity / Event','Money In','Money Out','Status','Notes'];
const FIN_TABS=[['dashboard','Dashboard'],['control','Control'],['lineitem','Line-Item Budget'],['baseline','Budget Baseline'],['transactions2026','Transactions-2026'],['reconciliation','Reconciliation'],['transactionlist','Transaction List'],['eventbudgets','Event Budgets']];
let finRows=[],finTab='dashboard',finEdit=-1,finFilter='',finBankBalance=0;
const $=id=>document.getElementById(id);
const fm=n=>'$'+(Number(n)||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
const fe=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=n=>Number(String(n||'').replace(/[^0-9.-]/g,''))||0;
const finStatus=(s,error=false)=>{ $('save-status').textContent=s; $('save-status').classList.toggle('error',error); };
async function finRequest(path,method='GET',body){const response=await fetch('https://sheets.googleapis.com/v4/spreadsheets/'+TH_SHEET_ID+path,{method,headers:{Authorization:'Bearer '+thToken,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});if(!response.ok){const detail=await response.json().catch(()=>({}));throw new Error(detail.error?.message||'Finance data could not be saved.')}return response.json();}
const finSettings=range=>'/values/'+encodeURIComponent("'Personal Finance Settings'!"+range);
const finRange=range=>'/values/'+encodeURIComponent("'"+FIN_SHEET.replace(/'/g,"''")+"'!"+range);
async function finInit(){
 const meta=await thSheets('?fields=sheets.properties(title)');
 if(!(meta.sheets||[]).some(s=>s.properties.title===FIN_SHEET)){
  await finRequest(':batchUpdate','POST',{requests:[{addSheet:{properties:{title:FIN_SHEET,gridProperties:{rowCount:1000,columnCount:11}}}}]});
  await finRequest(finRange('A1:K1')+'?valueInputOption=RAW','PUT',{values:[FIN_HEADERS]});
 }
 if(!(meta.sheets||[]).some(s=>s.properties.title==='Personal Finance Settings')){
  await finRequest(':batchUpdate','POST',{requests:[{addSheet:{properties:{title:'Personal Finance Settings',gridProperties:{rowCount:100,columnCount:2}}}}]});
  await finRequest(finSettings('A1:B2')+'?valueInputOption=RAW','PUT',{values:[['Setting','Amount'],['Bank available balance',0]]});
 }
 const settings=await finRequest(finSettings('A2:B2')+'?valueRenderOption=UNFORMATTED_VALUE');finBankBalance=num(settings.values?.[0]?.[1]);
 await finLoad();
}
async function finLoad(){const data=await finRequest(finRange('A2:K5000')+'?valueRenderOption=UNFORMATTED_VALUE');finRows=(data.values||[]).map((r,i)=>({r:r.concat(Array(11).fill('')).slice(0,11),sheetRow:i+2})).filter(x=>x.r[0]);finRender();}
function finVisible(){let rows=finRows;
 if(finTab==='transactions2026')rows=rows.filter(x=>String(x.r[1]).startsWith('2026'));
 if(finTab==='reconciliation')rows=rows.filter(x=>String(x.r[9]).toLowerCase()!=='cleared');
 if(finTab==='eventbudgets')rows=rows.filter(x=>x.r[6]);
 if(finFilter)rows=rows.filter(x=>x.r.join(' ').toLowerCase().includes(finFilter.toLowerCase()));return rows;
}
function finCards(rows){const income=rows.reduce((s,x)=>s+num(x.r[7]),0),expense=rows.reduce((s,x)=>s+num(x.r[8]),0),pending=rows.filter(x=>String(x.r[9]).toLowerCase()!=='cleared').reduce((s,x)=>s+num(x.r[7])-num(x.r[8]),0);return '<div class="finance-cards"><div><span>Money in</span><strong>'+fm(income)+'</strong></div><div><span>Money out</span><strong>'+fm(expense)+'</strong></div><div><span>Balance</span><strong>'+fm(income-expense)+'</strong></div><div><span>Pending net</span><strong>'+fm(pending)+'</strong></div></div>'}
function finTable(rows){return '<div class="table-scroll"><table><thead><tr><th>Date</th><th>Account</th><th>Payee / Description</th><th>Category</th><th>Subcategory</th><th>Activity</th><th>Money in</th><th>Money out</th><th>Status</th><th></th></tr></thead><tbody>'+rows.map(x=>'<tr><td>'+fe(x.r[1])+'</td><td>'+fe(x.r[2])+'</td><td>'+fe(x.r[3])+'</td><td>'+fe(x.r[4])+'</td><td>'+fe(x.r[5])+'</td><td>'+fe(x.r[6])+'</td><td>'+fm(x.r[7])+'</td><td>'+fm(x.r[8])+'</td><td><span class="status '+(x.r[9]==='Cleared'?'cleared':'pending')+'">'+fe(x.r[9]||'Pending')+'</span></td><td><button class="row-edit" data-row="'+x.sheetRow+'">Edit</button></td></tr>').join('')+'</tbody></table></div>'}
function finGroup(rows,index){const groups=new Map();for(const x of rows){const key=String(x.r[index]||'Uncategorized');const v=groups.get(key)||{in:0,out:0,count:0};v.in+=num(x.r[7]);v.out+=num(x.r[8]);v.count++;groups.set(key,v)}return '<div class="table-scroll"><table><thead><tr><th>Group</th><th>Transactions</th><th>Money in</th><th>Money out</th><th>Net</th></tr></thead><tbody>'+[...groups].sort((a,b)=>a[0].localeCompare(b[0])).map(([k,v])=>'<tr><td>'+fe(k)+'</td><td>'+v.count+'</td><td>'+fm(v.in)+'</td><td>'+fm(v.out)+'</td><td>'+fm(v.in-v.out)+'</td></tr>').join('')+'</tbody></table></div>'}
const finSum=(rows,col)=>rows.reduce((total,x)=>total+num(x.r[col]),0);
function finDashboard(){const now=new Date(),year=now.getFullYear(),month=String(now.getMonth()+1).padStart(2,'0'),thisMonth=finRows.filter(x=>String(x.r[1]).startsWith(year+'-'+month)),thisYear=finRows.filter(x=>String(x.r[1]).startsWith(String(year))),balance=finSum(finRows,7)-finSum(finRows,8),pending=finRows.filter(x=>x.r[9]!=='Cleared'),pendingNet=finSum(pending,7)-finSum(pending,8),cleared=balance-pendingNet;
 const tile=(label,value)=>'<div class="snapshot-tile"><small>'+label+'</small><strong>'+fm(value)+'</strong></div>';
 return '<div class="snapshot"><div class="snapshot-title"><strong>TisZod — Personal Financial Dashboard ('+year+')</strong><span class="live-marker">● LIVE · '+fe(now.toLocaleString())+'</span></div><p>Personal balances, transactions, and reconciliation</p><h3>CASH POSITION</h3><div class="snapshot-grid">'+tile('TOTAL BOOK BALANCE',balance)+tile('CLEARED BALANCE',cleared)+tile('PENDING NET',pendingNet)+'</div><h3>FINANCIAL PERFORMANCE</h3><div class="snapshot-grid">'+tile('NET THIS MONTH',finSum(thisMonth,7)-finSum(thisMonth,8))+tile('YEAR TO DATE INCOME',finSum(thisYear,7))+tile('YEAR TO DATE NET',finSum(thisYear,7)-finSum(thisYear,8))+'</div><h3>SPENDING & CONTROL</h3><div class="snapshot-grid">'+tile('YEAR TO DATE EXPENSES',finSum(thisYear,8))+tile('TOTAL TRANSACTIONS',finRows.length)+tile('BANK DIFFERENCE',finBankBalance-cleared)+'</div></div>';
}
function finControl(){const now=new Date(),year=now.getFullYear(),month=String(now.getMonth()+1).padStart(2,'0'),thisMonth=finRows.filter(x=>String(x.r[1]).startsWith(year+'-'+month)),thisYear=finRows.filter(x=>String(x.r[1]).startsWith(String(year))),balance=finSum(finRows,7)-finSum(finRows,8),pending=finRows.filter(x=>x.r[9]!=='Cleared'),pendingNet=finSum(pending,7)-finSum(pending,8),cleared=balance-pendingNet,diff=finBankBalance-cleared;
 const accounts=[...new Set(finRows.map(x=>String(x.r[2]||'Unspecified')))];
 const box=(title,items,tone='green')=>'<section class="control-box '+tone+'"><h3>'+title+'</h3><div>'+items.map(([label,value])=>'<p><span>'+fe(label)+'</span><strong>'+value+'</strong></p>').join('')+'</div></section>';
 return '<div class="control-intro"><strong>TisZod — Personal Financial Snapshot ('+year+')</strong><span>● LIVE · '+fe(now.toLocaleString())+'</span></div><div class="control-action"><button id="edit-bank" type="button">✎ Edit Bank Reconciliation</button></div><div class="control-grid">'+box('ACCOUNT BALANCES',[...accounts.map(a=>[a,fm(finRows.filter(x=>String(x.r[2]||'Unspecified')===a).reduce((n,x)=>n+num(x.r[7])-num(x.r[8]),0))]),['Total book balance',fm(balance)]])+box('BANK RECONCILIATION',[['Bank available balance',fm(finBankBalance)],['Cleared transactions',fm(cleared)],['Pending net',fm(pendingNet)],['Difference from cleared balance',fm(diff)],['Status',Math.abs(diff)<.005?'BALANCED':'REVIEW NEEDED']],'gold')+box('CURRENT MONTH',[['Income',fm(finSum(thisMonth,7))],['Expenses',fm(finSum(thisMonth,8))],['Net this month',fm(finSum(thisMonth,7)-finSum(thisMonth,8))]])+box('YEAR TO DATE',[['Income',fm(finSum(thisYear,7))],['Expenses',fm(finSum(thisYear,8))],['Net position',fm(finSum(thisYear,7)-finSum(thisYear,8))]])+'</div>';
}
function finRender(){const tabs=$('finance-tabs');tabs.innerHTML=FIN_TABS.map(([id,label])=>'<button type="button" data-tab="'+id+'" class="'+(id===finTab?'active':'')+'">'+label+'</button>').join('');const rows=finVisible(),title=FIN_TABS.find(x=>x[0]===finTab)[1];let grouping={lineitem:4,baseline:4,eventbudgets:6}[finTab];let content='<section class="finance-panel"><div class="panel-head"><h2>'+title+'</h2>'+(finTab==='dashboard'||finTab==='control'?'':'<label>Search <input id="finance-search" value="'+fe(finFilter)+'" placeholder="Search these records"></label>')+'</div>';
 if(finTab==='dashboard')content+=finDashboard();
 else if(finTab==='control')content+=finControl();
 else{content+=finCards(rows);if(!finRows.length)content+='<div class="empty-finance"><h3>Starting fresh at $0.00</h3><p>Add your first personal transaction.</p><button type="button" id="first-add">Add first transaction</button></div>';else if(!rows.length)content+='<p class="empty-finance">No records in this section yet.</p>';else content+=grouping!==undefined?finGroup(rows,grouping):finTable(rows)}
 $('finance-content').innerHTML=content+'</section>';const search=$('finance-search');search?.addEventListener('input',e=>{finFilter=e.target.value;const at=e.target.selectionStart;finRender();$('finance-search').focus();$('finance-search').setSelectionRange(at,at)});$('first-add')?.addEventListener('click',()=>finOpen());}
function finOpen(sheetRow){finEdit=sheetRow||-1;const form=$('transaction-form');form.reset();const item=finRows.find(x=>x.sheetRow===sheetRow);const fields=['id','date','account','payee','category','subcategory','activity','income','expense','cleared','notes'];if(item)fields.slice(1).forEach((f,i)=>form.elements[f].value=item.r[i+1]??'');else{form.elements.date.value=new Date().toLocaleDateString('en-CA');form.elements.cleared.value='Pending'}$('editor-title').textContent=item?'Edit transaction':'Add transaction';$('editor').showModal()}
$('finance-tabs').addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(b){finTab=b.dataset.tab;finFilter='';finRender()}});
$('finance-content').addEventListener('click',async e=>{const b=e.target.closest('[data-row]');if(b)finOpen(Number(b.dataset.row));if(e.target.closest('#edit-bank')){const answer=prompt('Bank available balance',finBankBalance.toFixed(2));if(answer===null)return;if(!/^\s*\$?\s*-?\d+(?:\.\d{1,2})?\s*$/.test(answer)){finStatus('Enter a valid dollar amount.',true);return}try{await finRequest(finSettings('B2')+'?valueInputOption=RAW','PUT',{values:[[num(answer)]]});finBankBalance=num(answer);finRender();finStatus('Bank balance saved.')}catch(err){finStatus(err.message,true)}}});
$('add').addEventListener('click',()=>finOpen());$('cancel').addEventListener('click',()=>$('editor').close());
$('transaction-form').addEventListener('submit',async e=>{e.preventDefault();const f=e.target;const income=num(f.elements.income.value),expense=num(f.elements.expense.value);if(income&&expense){finStatus('Enter money in or money out, not both.',true);return}if(!income&&!expense){finStatus('Enter an amount.',true);return}const existing=finRows.find(x=>x.sheetRow===finEdit);const row=[existing?.r[0]||crypto.randomUUID(),...['date','account','payee','category','subcategory','activity'].map(k=>f.elements[k].value.trim()),income||'',expense||'',f.elements.cleared.value,f.elements.notes.value.trim()];const button=f.querySelector('[type=submit]');button.disabled=true;finStatus('Saving…');try{if(existing)await finRequest(finRange('A'+finEdit+':K'+finEdit)+'?valueInputOption=RAW','PUT',{values:[row]});else await finRequest(finRange('A:K')+':append?valueInputOption=RAW&insertDataOption=INSERT_ROWS','POST',{values:[row]});$('editor').close();await finLoad();finStatus('Saved.')}catch(err){finStatus(err.message,true)}finally{button.disabled=false}});
$('export').addEventListener('click',()=>{const rows=[FIN_HEADERS,...finVisible().map(x=>x.r)];const csv=rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='TisZod-Finance-'+finTab+'.csv';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
window.thStart=finInit;
